services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mock-s3:
    image: motoserver/moto:latest
    ports:
      - "5000:5000"

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - S3_ENDPOINT_URL=http://mock-s3:5000
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    volumes:
      - prometheus_multiproc:/tmp/prometheus_multiproc
    depends_on:
      - redis
      - rabbitmq
      - mock-s3

  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info --concurrency=4
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - S3_ENDPOINT_URL=http://mock-s3:5000
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    volumes:
      - prometheus_multiproc:/tmp/prometheus_multiproc
    depends_on:
      - redis
      - rabbitmq
      - mock-s3

volumes:
  prometheus_multiproc: